# Generated by Django 5.2.10 on 2026-02-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título Obtenido')),
                ('logo', models.ImageField(upload_to='logos_educacion/')),
                ('fecha_graduacion', models.DateField(verbose_name='Fecha de Graduación')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Formación Académica',
                'ordering': ['-fecha_graduacion'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Ej: Ingeniero de Software Senior', max_length=200, verbose_name='Cargo / Título')),
                ('empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web de la Empresa')),
                ('logo', models.ImageField(help_text='Suba una imagen del logo (PNG/JPG)', upload_to='logos_empresas/', verbose_name='Logo de la Empresa')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si es el trabajo actual', null=True, verbose_name='Fecha de Término')),
                ('es_trabajo_actual', models.BooleanField(default=False, verbose_name='¿Trabajo Actual?')),
                ('descripcion', models.TextField(help_text='Describa sus logros y tareas principales.', verbose_name='Descripción de Responsabilidades')),
                ('pais', models.CharField(default='CL', max_length=100, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
