# Generated by Django 5.2.11 on 2026-04-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_educacion/'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='logo',
            field=models.ImageField(blank=True, help_text='Suba una imagen del logo (PNG/JPG)', null=True, upload_to='logos_empresas/', verbose_name='Logo de la Empresa'),
        ),
    ]
