# Generated by Django 5.2.11 on 2026-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reset_admin_retry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educacion',
            options={'ordering': ['-ano_egreso'], 'verbose_name': 'Educación', 'verbose_name_plural': 'Formación Académica'},
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='fecha_graduacion',
        ),
        migrations.AddField(
            model_name='educacion',
            name='ano_egreso',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de Egreso'),
        ),
        migrations.AddField(
            model_name='educacion',
            name='ano_ingreso',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de Ingreso'),
        ),
        migrations.AddField(
            model_name='educacion',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web de la Institución'),
        ),
    ]
