# Generated by Django 5.2.11 on 2026-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_educacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('categoria', models.CharField(choices=[('infraestructura', 'Infraestructura / DevOps'), ('backend', 'Backend Python'), ('base_datos', 'Bases de Datos'), ('ia_vision', 'IA / Visión Computacional'), ('web', 'Web Frontend'), ('legado', 'Sistemas Legados')], max_length=30)),
                ('url_doc', models.URLField(blank=True, help_text='Link a documentación oficial')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden dentro de la categoría')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
    ]
