# Generated by Django 5.2.11 on 2026-06-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_habilidad_icono_clase_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ruta", models.CharField(blank=True, max_length=255)),
                ("ts", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
                "ordering": ["-id"],
            },
        ),
    ]
