# Generated by Django 5.2.11 on 2026-07-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_visita"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Texto breve que invite a la persona a entrar y averiguar.",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text='A dónde lleva la tarjeta. Externo: "https://ingles.felixjimenez.cl". Interno: "/curriculum". Correo: "mailto:fvjpsg@gmail.com".',
                        max_length=300,
                        verbose_name="Enlace",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        default="🚀",
                        help_text="Ícono grande de la tarjeta. Un emoji: 🇬🇧 🖥️ 🛒 📜 🖼️ 🌐",
                        max_length=8,
                    ),
                ),
                (
                    "oferta",
                    models.CharField(
                        blank=True,
                        help_text='Franja resaltada opcional. Ej: "🎉 Inauguración: 5 lecciones por $3.000 · la 1ª gratis".',
                        max_length=160,
                        verbose_name="Oferta / destacado",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text='Etiqueta corta en la esquina. Ej: "En vivo", "Nuevo", "Próximamente".',
                        max_length=30,
                        verbose_name="Etiqueta",
                    ),
                ),
                (
                    "acento",
                    models.CharField(
                        blank=True,
                        help_text="Color hex opcional para el ícono y el botón. Ej: #10b981. Vacío = índigo por defecto.",
                        max_length=20,
                        verbose_name="Color de acento",
                    ),
                ),
                (
                    "externo",
                    models.BooleanField(
                        default=True,
                        help_text="Marcado para enlaces externos (otro subdominio o sitio). Desmarcado para páginas internas como /curriculum.",
                        verbose_name="Abrir en pestaña nueva",
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(
                        default=True,
                        help_text="Desmárcalo para ocultar la tarjeta sin borrarla.",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Menor número aparece primero."
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto (portada)",
                "verbose_name_plural": "Proyectos (portada)",
                "ordering": ["orden", "titulo"],
            },
        ),
    ]
